version: '3'

services:
  fargate-demo:
    container_name: fargate-demo
    image: dev-src-fargate-image
    build:
      context: ecs/src/.
      dockerfile: Dockerfile
    command: "https://github.com/AssemblyAI-Examples/audio-intelligence-dashboard/raw/master/gettysburg10.wav"
    ports:
      - 80:80
    expose:
      - "80"